version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql_CarShop
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: CarShopDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Abdullah159
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis_CarShop
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "CarShopRedis123"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_CarShop
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Abdullah159
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge